# Generated by Django 3.0.8 on 2020-07-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200709_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to='core.OTP'),
        ),
    ]
