# Generated by Django 3.0.8 on 2020-07-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='core.subCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='core.Vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.ManyToManyField(blank=True, to='core.PriceSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ManyToManyField(related_name='mrp_size', to='core.PriceSize'),
        ),
    ]
