# Generated by Django 3.0.8 on 2020-07-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200715_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.ManyToManyField(blank=True, related_name='discount_size', to='core.PriceSize'),
        ),
    ]
